---
- name: Stuff for working on Debian
  hosts: localhost
  vars:
    osusers:
      - ansible
      - tim
  tasks:

  - name: User
    user:
      name: "{{ item }}"
      state: present
      shell: /bin/bash
      password: "$6$2c3uRv3Dx2wt8nm2$sTk22Q2SBuPRE0i4wa5ZiWaNpgrozN2q.T4HA.cFHyfnCDWUAnyQFguLVA0hpFfV.yUvSNtyAB613IyQWFZFV1" # openssl passwd -6 -salt ABC yourpass
    loop: "{{ osusers }}"
    
  - name: bashrc for "{{ item }}"
    copy:
      src: files/.bashrc
      dest: "/home/{{ item }}/.bashrc"
      owner: root
      group: root
      mode: '0644'
    loop: "{{ osusers }}"

  - name: generate SSH DIR for "{{ item }}"
    file:
      path: "/home/{{ item }}/.ssh"
      state: directory
      owner: "{{ item }}"
      group: "{{ item }}"
      mode: '0600'
    loop: "{{ osusers }}"

  - name: generate SSH key "{{ item }}"
    openssh_keypair:
      path: "/home/{{ item }}/.ssh/id_rsa"
      type: rsa
      size: 4096
      group: "{{ item }}"
      owner: "{{ item }}"
      state: present
      force: no
    loop: "{{ osusers }}"

  - name: Configure sudo for user
    copy:
      src: files/sudo_users
      dest: /etc/sudoers.d/sudo_users
      owner: root
      group: root
      mode: '0644'

  - name: Enable Root Login
    lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin yes"
           state=present
           backup=yes
    notify:
      - restart ssh

  - name: Basic Packages
    package:
      name: "{{ item }}"
      state: present
    loop:
      - git
      - vim
      - tmux
      - sudo
      - net-tools
      - iproute2 #ss
      - apt-file
      - locate
      - ansible
      - iotop
      - sysstat #iostat
      - htop
      - yamllint
      - tldr
      - curl
      - wget
      - tcpdump
      - iptraf-ng
      - nethogs
      - iftop
      - nmon
      - openssh-server
      - openssh-client
      - openssl
      - bash-completion #https://www.mediamill.de/blog/2014/03/11/aktivieren-des-bash-completion-features-auf-einem-debian-system/

  - name: Configure vimrc
    copy:
      src: files/.vimrc
      dest: /root/.vimrc
      owner: root
      group: root
      mode: '0644'
      backup: true
  
  - name: Install glances prerequisites
    package:
      name: python3, python3-dev, python3-jinja2, python3-psutil, python3-setuptools, hddtemp, python3-pip, lm-sensors
      state: present

  - name: Install glances
    pip:
      name: glances

  - name: Check binary yq
    stat:
      path: /usr/bin/yq
    register: yq_file_path

  - name: Install yq
    command:
      cmd: wget https://github.com/mikefarah/yq/releases/download/v4.27.2/yq_linux_amd64 -O /usr/bin/yq
    register: yq_install
    when: not yq_file_path.stat.exists

  - name: Check yq file mode
    file:
      path: /usr/bin/yq
      mode: '0755'
      state: file
    when: yq_install

  handlers:
    - name: restart ssh
      service:
        name=sshd
        state=restarted
